name: Go Multi-platform Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送带有 'v' 前缀的标签时触发，如 v1.0.0

jobs:
  test:
    name: Test Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24' # 可以根据需要修改 Go 版本
          check-latest: true
      
      - name: Get dependencies
        run: go mod download
      
      - name: Run tests
        run: go test -v ./...